package HelloCorba;


/**
* HelloCorba/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./HelloCorba.idl
* Freitag, 7. November 2014 14:03 Uhr MEZ
*/

public interface HelloOperations 
{
  String sayHello ();
  void shutdown ();
} // interface HelloOperations
