package HelloCorba;


/**
* HelloCorba/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./HelloCorba.idl
* Dienstag, 4. November 2014 15:14 Uhr MEZ
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
