package HelloCorba;


/**
* HelloCorba/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./HelloCorba.idl
* Freitag, 7. November 2014 14:03 Uhr MEZ
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
